### ISSUE TITLE
Alternative Date adapters

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#1977]
Now that we have an `NgbDateAdapter`, it might be nice to bundle a couple of default ones with the library:

- [x] `NgbDateNativeAdapter` - as seen in the datepicker adapter demo to use with native JS date
- [ ] `NgbDateISOAdapter` - to conform with ISO 8601 Dates
- [ ] `NgbDateMomentAdapter` - for use with moment js

**Comment by msosa** [comment]
@maxokorokov do you want me to attempt in making this adapters? 

For the first one we take the one in the demo as you said, for the 2nd would you just take the substrings of the ISO 8601 dates and parse it that way? And for moment we would add the lib as a `devDepedency` and convert that object?

**Comment by maxokorokov** [comment]
@msosa, please do, if you have some time for this!

Start with a PR per adapter + tests.

I would put them under `datepicker/adapters` for now:
- native one should be the same as in demos
- iso 8601 should be something similar to what we have in date-formatter (`iso string` ←→ `NgbDateStruct`)
- moment is tricker, as I don't think we would want to put momentjs in peer dependencies of ng-bootstrap, so will have to think about it...

Later, from `2.0.0` it will be possible to make native adapter a default one

**Comment by msosa** [comment]
sounds good, i'll start off with those first 2 then

**Comment by jeroenheijmans** [comment]
For what it's worth, I've just crafted a Moment.js adapter with a few basic smoke tests. The full deal is [in a public gist](https://gist.github.com/jeroenheijmans/af473dad8ace3c5c4734588fca7d8b84), here's the adapter bits:

```typescript
// Might need to polyfill depending on needed browser support...
const isInt = Number.isInteger;

@Injectable()
export class NgbMomentjsAdapter extends NgbDateAdapter<moment.Moment> {

  fromModel(date: moment.Moment): NgbDateStruct {
    if (!date || !moment.isMoment(date)) {
      return null;
    }

    return {
      year: date.year(),
      month: date.month() + 1,
      day: date.date(),
    };
  }

  toModel(date: NgbDateStruct): moment.Moment {
    if (!date || !isInt(date.day) || !isInt(date.day) || !isInt(date.day)) {
      return null;
    }

    return moment(`${date.year}-${date.month}-${date.day}`, 'YYYY-MM-DD');
  }
}
```

I think there's a `util` based version of `isInt` in the library itself that might be useful instead of `Number.isInteger`.

But, at the bottom line, I guess @maxokorokov has a point that it's not so nice to pull in Moment.js as a dependency just to demonstrate something. Not sure what the solution would be for that (if any).

**Comment by maxokorokov** [comment]
@Braste it was added in cd14b96 and should be available since `2.1.0`

**Comment by tech-no-logical** [comment]
my super simple ISO implementation, fwiw :

``` javascript
function padNumber(value: number) {
  if (isNumber(value)) {
    return `0${value}`.slice(-2);
  } else {
    return '';
  }
}

@Injectable()
export class NgbIsoDateAdapter extends NgbDateAdapter<string> {
  fromModel(date: string): NgbDateStruct {

    const parsedDate = /(\d\d\d\d)-(\d\d)-(\d\d)/.exec(date);
    if (parsedDate) {
      return <NgbDateStruct>{ year: Number(parsedDate[1]), month: Number(parsedDate[2]), day: Number(parsedDate[3]) };
    } else {
      return null;
    }
  }
  toModel(date: NgbDateStruct): string {
    if (date) {
      return date.year + '-' + padNumber(date.month) + '-' + padNumber(date.day);
    } else {
      return null;
    }
  }
}
