### ISSUE TITLE
Timepicker

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/ng-bootstrap#24]
Implement timepicker from UI Bootstrap

Should note, this likely will need to be coordinated with the datepicker with the implementation of a default parsing service that can be optionally included that uses the Date constructor.

This should be flexible enough to accept other parsing mechanisms, i.e. moment.js, as long as a common interface is implemented.

**Comment by pkozlowski-opensource** [comment]
Moved from #242

Just documenting this so we don't lose it.  Per issues (and @wesleycho) in UIBS library, we should manage the hours, minutes, and second fields separately and not use a date object to back the data.   This does mean we need to handle the rolling ourselves, but I'm ok with that.

This also allows us to make a duration picker (using a common base) as well as people have asked for this in the UIBS library.

**Comment by sendilkumarn** [comment]
Ideally it should have 3 text boxes and a button [ AM/PM ]. it should accept input as date-time right? 
Is there any other things to be considered?

**Comment by pkozlowski-opensource** [comment]
>  it should accept input as date-time right? 

Rather not, see my comment above.

> Is there any other things to be considered?

Plenty... If you want to look into this one you should start with a design doc. See an example of a design doc and discussion we did for tooltips / popovers: https://github.com/ng-bootstrap/ng-bootstrap/issues/8#issuecomment-169721887

**Comment by sendilkumarn** [comment]
I think this docs I missed for scrollspy. I will do this one here.

**Comment by sendilkumarn** [comment]
@pkozlowski-opensource something like [this](https://docs.google.com/document/d/1EAZ8oERx5dBRS3-T6xaqAZ2-PBAXaOvqhA-gRUxEAzA/edit?usp=sharing)  would do? 

note: this will be my first doc. bare with if there are any errors :)

**Comment by sendilkumarn** [comment]
> don't over-engineer the API
>  duration mode 

👍 

> 2-3 separate input
> three separate properties

exactly that has to be there.

> timezone 

lets stand out of it as far as we can.

>  meridian field / step option

Few of my applications, we used it with ui-bootstrap and the response is good for that. But yes agree their use case are not common. But I think this one we can add.

**Comment by sendilkumarn** [comment]
Added duration-mode option. Updated doc

https://docs.google.com/document/d/1EAZ8oERx5dBRS3-T6xaqAZ2-PBAXaOvqhA-gRUxEAzA/edit#heading=h.97mxnaikvwpb

**Comment by icfantv** [comment]
Any reason the duration mode can't just be a directive like we do on alerts?  If it's there it's implied that it's on, I don't think it needs to be an actual flag.

**Comment by sendilkumarn** [comment]
Since we will be having few checks based on duration stuff, thought of having it as a flag.

**Comment by pkozlowski-opensource** [comment]
@sendilkumarn your document doesn't have rights properly set (I can't comment on it). Please push the right buttons so we all can collaborate on this doc. 

Here are just few high-level remarks before I can comment on the doc:
* [ ] - not sure what you are proposing for time parsing / formatting. What a user would use as a model? A string? A data structure?
* [ ] - there are no details on integration with ngModel directive (time-pickers on inputs)
* [ ] - there are no details on triggers (how a time-picker on input gets opened / closed)
* [ ] - there is proposal for rendering (how do we render up / down arrows knowing that BS4 doesn't provide icons)

**Comment by pkozlowski-opensource** [comment]
One other remark: while working on design docs try to focus on usage (what do I need to do / write as a user and what happens when I interact with the control). Impl details are important but less so then the API.

**Comment by sendilkumarn** [comment]
Have given edit access to @pkozlowski-opensource @Foxandxss 

cannot find email of @icfantv . can help?

**Comment by pkozlowski-opensource** [comment]
@sendilkumarn left some comments in the doc. More importantly, though, the doc is missing essential elements listed before: https://github.com/ng-bootstrap/ng-bootstrap/issues/24#issuecomment-232338006

**Comment by sendilkumarn** [comment]
@pkozlowski-opensource I didn't quite get the third point in the comment?  

I have added remaining comments in that document.

**Comment by pkozlowski-opensource** [comment]
> I didn't quite get the third point in the comment?

Scratched this for now.

**Comment by pkozlowski-opensource** [comment]
@sendilkumarn so I was just toying with different parts of the timepicker support and this is where I got: https://plnkr.co/edit/aIDYlK5lq58Tb6TvQ1kF?p=preview 

It is still missing a lot of functionality (doesn't support any options you've listed, don't have proper formatting etc.) but I think this is a skeleton of where I would like it to go. If it makes sense for you could you turn it into a PR with proper code, tests and complete support for all the options? 

Let me know if you've got any questions. @wesleycho might have some additional input as well.

**Comment by wesleycho** [comment]
This looks pretty solid as a step towards how it should work.

We still need to wrestle with validation, but I'm not sure if that's built into Angular's form controls yet.

**Comment by icfantv** [comment]
I agree with @wesleycho, this is a good first step.  RE forms, don't forget they're supposed to be extracted out and I don't know if that means they're getting changed in the process or just moved.  @robwormald may know...

**Comment by sendilkumarn** [comment]
`ngModelChange` we have to rethink on this

[plunkr - just updated few basics ](https://plnkr.co/edit/GtHHMf5NWOhjJevKP4VO?p=preview)

**Comment by pkozlowski-opensource** [comment]
I'm trying to make timepicker display looks decent and I'm not getting great results... This is where it starts to resemble timepicker but we would have to make it sleek: https://plnkr.co/edit/ipxNLJGIXAAsVOVP60DK?p=preview

Could anyone give me a hand with this?

**Comment by RobJacobs** [comment]
[This](http://jdewit.github.io/bootstrap-timepicker/) implementation has the timepicker in a popup which I think is less obtrusive and follows the datepicker implementation.

**Comment by sendilkumarn** [comment]
I will :)

**Comment by pkozlowski-opensource** [comment]
@RobJacobs I saw this one but:
* it is based on BS3
* doesn't look that great...

@sendilkumarn thinx for the proposals. There are some interesting ideas but IMO buttons look kind of gross.... We need a light, beautiful design (and I know that "beautiful" is highly subjective....)

**Comment by RobJacobs** [comment]
@pkozlowski-opensource I agree on the look, but wanted to suggest using a popup for displaying the inputs with buttons.  I've run into issues trying to keep other input fields horizontally aligned with the timepicker.

**Comment by pkozlowski-opensource** [comment]
@RobJacobs not sure what you mean by "popup" (did you mean popover???) but please put your ideas in a plunk - will be easier to discuss.

**Comment by pkozlowski-opensource** [comment]
Initial version of timepicker just landed via 6fcaea568e64c713f7607b4d846c52218362029d and f4388994bcf90d69e0356077b81164189ffd92bd.

@icfantv feel free to send PR(s) to any remaining look & feel changes you would like to introduce.

**Comment by icfantv** [comment]
@pkozlowski-opensource roger that.
