### ISSUE TITLE
Chore for 5.0.0

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#3016]
- [x] bump node version to `10` (#3195)
- [x] bump Angular to ~`7.???`~ `8.0.0`, Bootstrap to `4.3`, TypeScript to `3.2.4` and other deps (#3220)
- [x] remove deprecated `.forRoot()` (#3015)

**Comment by mendeza** [comment]
Unless you're in a hurry, why not wait for Angular 8.0.0?

**Comment by benouat** [comment]
> * remove deprecated `.forRoot()` (#3015)

Done via 83f79cfe48cdadbf5147b67ee3671b0047b7d4b5

> * bump Angular to 8.0.0, Bootstrap to 4.3, TypeScript to 3.2.4 and other deps

Done via #3220
