### ISSUE TITLE
Playwright migration

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#3988]
Proof-of-concept PR → #3966 

- [x] **Demo App** → #3966
- [x] **SSR App** →#3967

**E2E App**
- [x] Datepicker → #3993
- [x] Dropdown → #3983
- [x] Modal → #4001
- [x] Popover → #3987
- [x] Timepicker → #3990
- [x] Tooltip → #3989
- [x] Typeahead → #3996

--- 
- [x] use `test.page` instead of `page()` → #4011
- [x] refactor `tools.po` → #4019
- [x] review the way pages are navigated (`openUrl` in  `tools.pw-po`): reload/click/goto depending on the browser
- [x] remove protractor completely → #4018
- [x] remove `expect(await ...$()).toBeThuthy()` constructs → #4000

**Comment by maxokorokov** [comment]
Closing this as most of the work is done
