### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#4178]
Latest releases:
- ng-bootstrap 10 with Angular 12 and BS 4.5 (Stable)
- ng-bootstrap 11 with Angular 13 and BS 4.6 → [RC.0](https://github.com/ng-bootstrap/ng-bootstrap/releases/tag/11.0.0-rc.0)
- ng-bootstrap 12 with Angular 13 and BS 5 → [Beta.4](https://github.com/ng-bootstrap/ng-bootstrap/releases/tag/12.0.0-beta.4)

---
Internal issues:
- [x] Looks like StackBlitz doesn't work with Angular 13 yet → https://github.com/stackblitz/core/issues/1657, so no demo site update
- [x] `eslint-plugin-deprecation` doesn't support `eslint 8`→ using `angular-eslint 12` version at the moment
- [x] e2e coverage is not working. Looks like issues with `coverage-istanbul-reporter` → temporarily disabling custom webpack config
- [x] BS warnings in e2e tests in console → temporarily disabling warning checks
- [x] ~~unit tests for schematics are broken due to `externalSchematic` calling `@angular/localize` ESM issues → temporarily disabling~~ (Fixed in Angular 13.0.2 with #4183)
- [x] ~~no support for Angular 13 in `ngx-build-plus` → no e2e coverage at the moment~~ → moved to @angular-builders with #4180

**Comment by inexuscore** [comment]
Any idea when Angular 13 will be supported for the Bootstrap 4.x version? We're trying to update to Angular 13 but a few libraries have conflicting peer dependencies. It would be great to bump the versions and target ng 13 if it's not difficult. Thank you very much.

**Comment by terencehonles** [comment]
@maxokorokov any thoughts on when the move to rxjs 7.4 might happen? This is possible in Angular 13, but rxjs is declared as using `^6.5.5` so I'm not sure if that would be something that would happen in ng-bootstrap 11 or ng-bootstrap 12. I can see what breaks when migrating, but not sure what branch to target and when/if the changes would be merged.

**Comment by maxokorokov** [comment]
@terencehonles we'll do the same as all Angular packages and have `"rxjs": "^6.5.3 || ^7.4.0"` in peer deps the next 11 release

**Comment by maxokorokov** [comment]
@terencehonles several issues we're currently facing:
- no `ngx-build-plus` support for Angular 13
- no `angular-eslint` support for Angular 13

I should do the `RC` release today though to do some more tests  on our side (schematics, stackblitzes, etc.)

**Comment by terencehonles** [comment]
> * no `angular-eslint` support for Angular 13

Do you want to use the prerelease as mentioned in https://github.com/angular-eslint/angular-eslint/pull/780 / https://github.com/angular-eslint/angular-eslint/pull/780#issuecomment-958774144 ?

I could open a PR for that, but not sure if you'd want to manage that yourself.

**Comment by terencehonles** [comment]
> * no `ngx-build-plus` support for Angular 13

Also, looking at `ngx-build-plus` it looks like development has stalled a bit and when looking it is used in this repo I'm wondering if it makes more sense to just switch to https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack. I believe it will provide the same functionality (using [the custom webpack config e2e-app/coverage.webpack.js](https://github.com/ng-bootstrap/ng-bootstrap/blob/f13d1ac8ea4877a956911da71e243d43bfeb1277/e2e-app/coverage.webpack.js)) and it's already updated to Angular 13 (and the Angular team recently asked to move the Bazel builder there https://github.com/just-jeb/angular-builders/issues/1047 and PRd https://github.com/just-jeb/angular-builders/pull/1048)

Same comment about opening a PR for that and that could be done on `master` for Angular 12, I'm not sure where the Angular 11 WIP branch is.

**Comment by sysmat** [comment]
> Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
> - @ng-bootstrap/ng-bootstrap [es2015/esm2015] (git+https://github.com/ng-bootstrap/ng-bootstrap.git)
> Encourage the library authors to publish an Ivy distribution.

ng13

**Comment by terencehonles** [comment]
> * [ ]  e2e coverage is not working. Looks like issues with `coverage-istanbul-reporter` → temporarily disabling custom webpack config

I believe this is supposed to be `coverage-istanbul-loader`? What was the issue? Did you want me to look a little into this? I'm not sure if this is related to:

> [Changelog 🔗](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#angular-devkitbuild-angular-3): Support for karma-coverage-instanbul-reporter has been dropped in favor of the official karma coverage plugin karma-coverage.

That's specifically for Karma, but not sure if the support was just dropped because there didn't need to be 2 different packages or if something else changed.

**Comment by terencehonles** [comment]
> * [ ]  unit tests for schematics are broken due to `externalSchematic` calling `@angular/localize` ESM issues → temporarily disabling

I got with https://github.com/ng-bootstrap/ng-bootstrap/pull/4183 by pulling in https://github.com/angular/angular/pull/44016. I wasted a bit of time trying to get jasmine to run the test as an ESM, but then I saw the change on Angular's side :sweat_smile:.

**Comment by shendbajgora** [comment]
@maxokorokov 
I'm using angular 13, can't wait for 11.0.0-rc.1 release candidate xD.
Is it possible that this is going to happen on this weekend?

**Comment by internalsystemerror** [comment]
@angular-eslint/angular-eslint v13 just dropped FYI

**Comment by internalsystemerror** [comment]
@maxokorokov hopefully to save you some time, I thought I'd upload the results of my testing. https://github.com/ng-bootstrap/ng-bootstrap/compare/master...internalsystemerror:feature/ng13

The karma tests pass locally and the only thing outstanding would be linting errors which I'm unsure how you wish to resolve:
```
Linting "ng-bootstrap"...

/home/ise/projects/ng-bootstrap/ng-bootstrap/src/datepicker/datepicker-navigation-select.ts
  47:13  error  Output bindings, including aliases, should not be named as standard DOM events  @angular-eslint/no-output-native

/home/ise/projects/ng-bootstrap/ng-bootstrap/src/datepicker/datepicker-navigation.ts
  55:13  error  Output bindings, including aliases, should not be named as standard DOM events  @angular-eslint/no-output-native

/home/ise/projects/ng-bootstrap/ng-bootstrap/src/dropdown/dropdown.ts
  172:10  error  Input bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)  @angular-eslint/no-input-rename

/home/ise/projects/ng-bootstrap/ng-bootstrap/src/modal/modal-window.ts
  63:11  error  Output bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)  @angular-eslint/no-output-rename

/home/ise/projects/ng-bootstrap/ng-bootstrap/src/typeahead/typeahead-window.ts
  91:11  error  Output bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)  @angular-eslint/no-output-rename
  91:11  error  Output bindings, including aliases, should not be named as standard DOM events           @angular-eslint/no-output-native
  ```

**Comment by divdavem** [comment]
For info, I have opened https://github.com/angular/angular-cli/pull/22220 to fix the issue related to code coverage in e2e tests.

**Comment by yktoo** [comment]
Hey guys, do you have any ETA in mind for the 11.0.0 release?

**Comment by divdavem** [comment]
For info, I have opened #4193 to re-enable code coverage in e2e tests (now that [angular/cli 13.0.4](https://github.com/angular/angular-cli/releases/tag/13.0.4) is released)

**Comment by pantonis** [comment]
Any update on this. getting errors while trying to install. I used --force to overcome this.

**Comment by markwhitfeld** [comment]
FYI, StackBlitz now supports Angular 13:
> Great news! Support for Angular 13 has finally rolled out.
...
For the next day or two (until 12 December 2021), there is a possibility of an initial slow down in starting up the dev server or running NGCC (or potentially even timeouts) as the packages repopulate into the cache as they are used, but it should come right after a refresh or two if you do have any issues. Anything else should be reported as a new issue.

Related StackBlitz issue comment: https://github.com/stackblitz/core/issues/1657#issuecomment-989779722

**Comment by divdavem** [comment]
For info, I have opened #4198 to fix StackBlitz examples now that StackBlitz supports Angular 13.

**Comment by gloriousjob** [comment]
v1.3.2 of eslint-plugin-deprecation supports eslint 8, as of v.1.3.0 (yesterday).

**Comment by divdavem** [comment]
> v1.3.2 of eslint-plugin-deprecation supports eslint 8, as of v.1.3.0 (yesterday).

I have opened #4202 to update `@angular-eslint/schematics` and `eslint-plugin-deprecation`.

**Comment by terencehonles** [comment]
Do we have any more release blockers (other than the open PR #4202)? Looks like @divdavem took care of quite a few things :muscle:

**Comment by fbasso** [comment]
The new 11.0.0 has been released. Thank you all for your efforts !

**Comment by ETMitch21** [comment]
> could you please let me know if this is fixed or going to be fixed soon:
> 
> ```
> >npm install @ng-bootstrap/ng-bootstrap@bootstrap5
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: client-app@0.0.0
> npm ERR! Found: @angular/compiler@13.0.3
> npm ERR! node_modules/@angular/compiler
> npm ERR!   @angular/compiler@"~13.0.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/compiler@"13.1.0" from @angular/localize@13.1.0
> npm ERR! node_modules/@angular/localize
> npm ERR!   peer @angular/localize@"^13.0.0" from @ng-bootstrap/ng-bootstrap@12.0.0-beta.4
> npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
> npm ERR!     @ng-bootstrap/ng-bootstrap@"12.0.0-beta.4" from the root project
> ```

Did you get a fix for this? I'm experiencing this today as well.

**Comment by terencehonles** [comment]
@ETMitch21 If you're installing the bootstrap5 branch you should be posting your questions in #3899. You can still tag a user and quote a comment from this issue in that one if you find it might be helpful context.

**Comment by adrianord** [comment]
@terencehonles I'm getting the same issues when using version 11
```
> npm install @ng-bootstrap/ng-bootstrap
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: shopcart@0.0.0
npm ERR! Found: @angular/core@13.2.1
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"13.2.1" from @angular/animations@13.2.1
npm ERR!   node_modules/@angular/animations
npm ERR!     peerOptional @angular/animations@"13.2.1" from @angular/platform-browser@13.2.1
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"13.2.1" from @angular/forms@13.2.1
npm ERR!       node_modules/@angular/forms
npm ERR!         @angular/forms@"~13.2.0" from the root project
npm ERR!       3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!     @angular/animations@"~13.2.0" from the root project
npm ERR!   peer @angular/core@"13.2.1" from @angular/common@13.2.1
npm ERR!   node_modules/@angular/common
npm ERR!     peer @angular/common@"13.2.1" from @angular/forms@13.2.1
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"~13.2.0" from the root project
npm ERR!     peer @angular/common@"13.2.1" from @angular/platform-browser@13.2.1
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"13.2.1" from @angular/forms@13.2.1
npm ERR!       node_modules/@angular/forms
npm ERR!         @angular/forms@"~13.2.0" from the root project
npm ERR!       3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!     3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!   5 more (@angular/forms, @angular/platform-browser, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @ng-bootstrap/ng-bootstrap@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/core@13.2.2
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"13.2.2" from @angular/forms@13.2.2
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"~13.2.0" from the root project
npm ERR!     peer @angular/forms@"^13.0.0" from @ng-bootstrap/ng-bootstrap@11.0.0
npm ERR!     node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!       @ng-bootstrap/ng-bootstrap@"*" from the root project
```
It seems that the support for angular 13 does not support anything over angular 13.0.x

**Comment by internalsystemerror** [comment]
> It seems that the support for angular 13 does not support anything over angular 13.0.x

@adrianord I've been using this version since it was released with no issues. Currently on Angular 13.2.2. I suggest you open a new issue if you're certain it's an issue with this package.

**Comment by Alex3917** [comment]
@[adrianord](https://github.com/adrianord) Did you try deleting your package-lock.json and your node_modules folder, and then re-installing your dependencies? I always get those kinds of errors when upgrading Angular unless I do that.

**Comment by devoto13** [comment]
This is a result of a badly designed package manager. See e.g. https://github.com/ng-bootstrap/ng-bootstrap/issues/3970#issuecomment-767498880 or a billion of similar issues.

Use `npm i --legacy-peer-deps` as a workaround.

**Comment by adrianord** [comment]
@internalsystemerror @Alex3917 @devoto13 Thanks for the help guys, I was looking for an issue about this, I guess I was just using all the wrong keywords.

This was on a brand new angular project, using `nvm install --lts` and updating npm just for reference. It does sound like it's most likely an issue with npm like @devoto13 pointed to.

**Comment by hpardess** [comment]
```
$ npm install --save @ng-bootstrap/ng-bootstrap
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: app-web@0.0.0
npm ERR! Found: @angular/core@13.3.8
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"13.3.8" from @angular/animations@13.3.8
npm ERR!   node_modules/@angular/animations
npm ERR!     peerOptional @angular/animations@"13.3.8" from @angular/platform-browser@13.3.8
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"13.3.8" from @angular/forms@13.3.8
npm ERR!       node_modules/@angular/forms
npm ERR!         peer @angular/forms@">=13.0.0 <14.0.0" from @ng-select/ng-select@8.1.1
npm ERR!         node_modules/@ng-select/ng-select
npm ERR!         1 more (the root project)
npm ERR!       4 more (@angular/platform-browser-dynamic, @angular/router, ...)
npm ERR!     @angular/animations@"~13.3.0" from the root project
npm ERR!   peer @angular/core@"13.3.8" from @angular/common@13.3.8
npm ERR!   node_modules/@angular/common
npm ERR!     peer @angular/common@"13.3.8" from @angular/forms@13.3.8
npm ERR!     node_modules/@angular/forms
npm ERR!       peer @angular/forms@">=13.0.0 <14.0.0" from @ng-select/ng-select@8.1.1
npm ERR!       node_modules/@ng-select/ng-select
npm ERR!         @ng-select/ng-select@"^8.1.1" from the root project
npm ERR!       1 more (the root project)
npm ERR!     peer @angular/common@"13.3.8" from @angular/platform-browser@13.3.8
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"13.3.8" from @angular/forms@13.3.8
npm ERR!       node_modules/@angular/forms
npm ERR!         peer @angular/forms@">=13.0.0 <14.0.0" from @ng-select/ng-select@8.1.1
npm ERR!         node_modules/@ng-select/ng-select
npm ERR!         1 more (the root project)
npm ERR!       4 more (@angular/platform-browser-dynamic, @angular/router, ...)
npm ERR!     6 more (@angular/platform-browser-dynamic, @angular/router, ...)
npm ERR!   8 more (@angular/forms, @angular/platform-browser, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @ng-bootstrap/ng-bootstrap@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/core@13.3.11
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"13.3.11" from @angular/forms@13.3.11
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"~13.3.0" from the root project
npm ERR!     peer @angular/forms@"^13.0.0" from @ng-bootstrap/ng-bootstrap@12.1.2
npm ERR!     node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!       @ng-bootstrap/ng-bootstrap@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
Facing same error with Angular v13.3

**Comment by hpardess** [comment]
```
$ ng add @ng-bootstrap/ng-bootstrap
ℹ Using package manager: npm
⚠ Unable to find compatible package. Using 'latest' tag.
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

The package @ng-bootstrap/ng-bootstrap@12.1.2 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xyz-web@0.0.0
npm ERR! Found: @angular/common@14.0.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from @ng-bootstrap/ng-bootstrap@12.1.2
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"12.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/dream/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dream/.npm/_logs/2022-06-23T07_55_43_813Z-debug-0.log
✖ Packages installation failed, see above.
```
Facing same error with Angular v14
npm v8.12.2
