### ISSUE TITLE
Angular 17 + Bootstrap 5.3 support

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#4598]
Latest release with all this is `16.0.0-rc.2` under `@ng-bootstrap/ng-bootstrap@next`:

- `next` → `16.0.0-rc.2`
- `latest` → `15.1.2`

---

- [x] ~~Migrate to `Bootstrap 5.3`~~ (#4554)
- [x] ~~Adapt demo site for dark mode~~
- [x] ~~use `inject` where possible~~ (#4587)
- [x] ~~Migrate to `17-rc.3`~~ (#4597)
- [x] ~~Remove old `accordion` implementation~~ (#4600)
- [x] ~~`@angular` → final v17~~ (#4604)
- [x] ~~`@angular-eslint` → v17~~ (#4619)
- [x] ~~`@angular-builders/custom-webpack` → v17 (e2e coverage is disabled at the moment)~~(#4619)
- [x] ~~new control flow syntax~~ (#4624)
- [x] ~~stacked progressbar~~ (#4621)

---

Notes:

- ~~new control flow across library code and demos will arrive later as IDE/prettier support is not there yet~~
- esbuild for the demo site **kinda** works. Some issues with static resources and `bootstrap-icons` left

**Comment by bastienmoulia** [comment]
> * new control flow across library code and demos will arrive later as IDE/prettier support is not there yet

Looks like it's done: https://prettier.io/blog/2023/11/13/3.1.0#angular
