### ISSUE TITLE
Angular 18

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#4703]
Support for Angular 18

---

Initial release won't support zoneless change detection. Please open separate issues for this.

- [x] ~~Bump Angular dependencies and fix deprecations~~ (#4704)
- [x] ~~Bump `angular-eslint`~~ (#4710)
- [x] ~~Align with latest CLI configuration~~ (#4710)
- [x] ~~Fix `@for` tracking expressions giving warnings~~ (#4713)
- [x] Bump `@angular-builders/custom-webpack`

**Comment by sysmat** [comment]
it should be ported in the way `provideExperimentalZonelessChangeDetection`  will work

**Comment by ivebeenlinuxed** [comment]
@sysmat I can confirm issues with zoneless change detection. I run modal.open() and although the content is loaded into the modal window, the window never adds the "show" class. It thus remains in front of all content, but fully transparent.

I have a hunch that it's something to do with the way ngbTransition and zone work together, but I'm not a zone.js expert. Link below to the potentially offending line - but I've only done a quick manual code review. I'll see if I can find time to test.

https://github.com/ng-bootstrap/ng-bootstrap/blob/b5d5febde5691286211dd2401c2cb5334db0851f/src/util/transition/ngbTransition.ts#L67C3-L67C27

**Comment by sysmat** [comment]
@ivebeenlinuxed it could be, maybe for ref material.angular was ported to zonless.

**Comment by ivebeenlinuxed** [comment]
I have just set the option {animation: false} on the modal and things look much better. For now, I'm going to survive on this workaround:

```
modalService.open(this.modalRef, { centered: true, animation: false })
```

**Comment by foxyyyyyyyyyyyyy** [comment]
Is there any info when it will get released for angular 18?

**Comment by tony1658** [comment]
To find out in which tests the `@for` errors occur, you can temporarily use the  `karma-spec-reporter` package.
```js
config.set({
  ...
  plugins: [
    ...
    require('karma-spec-reporter')
  ],
  reporters: ['spec'],
  ...
});
```

**Comment by tony1658** [comment]
At the time of writing, the latest version of `@angular-builders/custom-webpack` is [18.0.0-beta.3](https://github.com/just-jeb/angular-builders/compare/@angular-builders/custom-webpack@17.0.3-beta.1...@angular-builders/custom-webpack@18.0.0-beta.3). The only breaking change is updating to Angular 18 (see their [changelog](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/CHANGELOG.md)) but I suggest waiting till a stable version before bumping the package version.

**Comment by mdmsb** [comment]
Should i downgrade angular to 17 or is there a way to still install in angular 18?

**Comment by tony1658** [comment]
@mdmsb you'll get a conflicting peer dependency warning. 

As a hacky workaround you could use `npm i --force` but I would suggest downgrading back to Angular 17 for now and waiting till ng-bootstrap releases a stable version which supports Angular 18.

**Comment by sysmat** [comment]
@mdmsb I upgrade to ng 18 with npm force and work fine. Don't use ng experimental zonless provider in app config

**Comment by EwertonRicardo** [comment]
Hello, guys. 

Is there any news about the update?

**Comment by voi99** [comment]
+1

**Comment by RichardBoyder** [comment]
same here is there any news when Bootstrap will be sorted to work with angular 18?

**Comment by sysmat** [comment]
- "@ng-bootstrap/ng-bootstrap": "^17.0.0", zoneless (provideExperimentalZonelessChangeDetection) not working

**Comment by maxokorokov** [comment]
@sysmat #4709, also please see release notes and #4714

**Comment by sysmat** [comment]
@maxokorokov thx, my bad
