### ISSUE TITLE
AoT for our demo site

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#542]
This is a meta-issue listing all the tasks leading us towards using offline compilation for the demo site:
- [x] - migrate to angular rc.5 - #535
- [x] - make sure that all fields / methods accessed from templates are public - #541
- [x] - evaluate WebPack 2.0 vs. Rollup for the production build and dev workflow
- [ ] - switch to WebPack 2.0 / Rollup
- [ ] - remove any calls to `require` if we decide to go with Rollup - #421
- [ ] - check if we need to switch from `template` => `templateUrl` in `@Component`
- [ ] - try out things and discover more tasks

**Comment by wesleycho** [comment]
The AoT compiler works with `templateUrl` if I remember correctly.

We need to remove `require` usage - this means we need to investigate how to integrate the prismjs syntax highlighting into the demos while still retaining the benefits of AoT compilation. We may need to wire up prismjs as an npm script to be run before ngc as opposed to its current usage as a Webpack loader.

**Comment by tinchou** [comment]
You can probably close this already :)

**Comment by pkozlowski-opensource** [comment]
@tinchou I've re-purposed this issue to track work needed to support AoT for our demo site.

**Comment by pkozlowski-opensource** [comment]
I'm starting to evaluate our demo site speed (load time / first paint) and comparing:
* WebPack 1.0 with JiT (current solution)
* Rollup with AoT
* WebPack 2.0 with JitT / AoT

All the numbers below are assuming: Chrome 53 in incognito mode (no extensions), no polyffils, no code highlight in code examples.

Setup | `DomContentLoaded` (ms) | Bundle size (kb, min+gzip)
------------ | ------------- | -------------
Rollup (AoT) | 430| 228
