### ISSUE TITLE
datepicker: visual improvements

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#706]
Datepicker's look & feel could use some love. Few ideas:
- [ ] get more space between days and different sections
- [x] we should be changing day's background in datepickers to light gray or sth when a user mouse-hovers over a given day.
- [ ] make navigation part visually separated from the calendar part

**Comment by c1rus** [comment]
What about adding some extra classes on current date and weekends?

**Comment by skendrot** [comment]
Looking for this as well. The current spacing is too tight and makes it unable to view the year in the dropdown
