### ISSUE TITLE
Datepicker evolution

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#862]
The datepicker will evolve. This is the issue to track down future enhancements, progress, discussion, etc:
- [x] Date range selection (#753)
- [x] Multiple months display (#977)
- [x] Visual improvements for default view (#706)
- [x] Ensure additional calendars support (#656)
- [x] Keyboard navigation (#1551)
- [x] Allow for custom date model (#1816)
- [x] Custom date models (#1979)
- [ ] Navigation customization / replacement
- [ ] Week numbers, weekdays and month names custom display (#1060)
- [x] Add content to datepicker template (#1197)

A little more details in the following [document](https://docs.google.com/document/d/1QFBpWNLH4YdxTE_gtYmHlBdknjpqTXJAjYuFHg32Q3k/edit?usp=sharing). Feel free to suggest and comment.

**Comment by ravipunjwani** [comment]
@maxokorokov I would suggest a few more. Please consider if possible.

- [ ] Configuration of HTML datepicker fallback for mobile devices (optional configuration).
- [ ] The current datepicker works great with larger screens but in mobile if the input-box is placed to the right corner, the datepicker popover gets trimmed due to screen boundaries.
- [ ] Custom formatting of date. Current workaround is way longer and would be great if it just allows with simple date format strings like "dd-MMM-yyyy" so it would just work.

**Comment by aitboudad** [comment]
can we have also support for `Date & Time Picker` ?

**Comment by ErgoSoftUK** [comment]
Are there any plans to implement a "month-year" picker (http://jsfiddle.net/brunodd/k5zookLt/20/)

**Comment by maxokorokov** [comment]
@ErgoSoftUK I was thinking about it **very** long-term, but definitely not in the nearest future, as there are plenty more priority use cases. Unless someone wants to help and do it of course :)

**Comment by ErgoSoftUK** [comment]
@maxokorokov Fair enough, thanks for the response max.  I think I also spotted a bug in there.  In the demo for the popup (with input box), if you enter an invalid year (just enter "33333") then click the pop-up icon, chrome tends to completely freeze.

**Comment by PEsteves8** [comment]
+1 to the suggestion of custom date formats on the input view. It would be nice to have full names for months (or event possibly weekdays), for instance.

**Comment by rodrigofns** [comment]
@ravipunjwani What's the current workaround to custom format a date, like "dd-mm-yyyy"?

**Comment by coutin** [comment]
I'm currently working on the datepicker keyboard navigation and visual improvment, and figure out that we are kind of stuck because of https://github.com/angular/angular/issues/12818.

In order to make the focus on the right element, the QueryList issue should be solved. As of now, I'm not able to access the ElementRef of each DayTemplate (as it's done in Accordion) and it seems related to that.

Then how should this be implemented, does it have to be fully customizable for to any custom Day view, or this should be independent  ?

**Comment by ravipunjwani** [comment]
@rodrigofns nothing yet, I was about to implement the custom format but couldn't spend much time on it. As we're still on development, it didn't get much urgent for me yet. Rather I would wait for quick configurable date-picker.

**Comment by divdavem** [comment]
@achimha I have opened a PR for keyboard navigation: #1417 
@maxokorokov Do you think we could merge it?

**Comment by sanspace** [comment]
Is there or can there be a config to make it act like a month picker? Just to select the MM/YY.
